title: Welcome to Stalking Lena 
author: Lena Park
email: lenapark0122@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 My name is Lena and I attend East Brunswick High School. I can finish a whole cheesecake by myself in one sitting yet am a varsity athelete.
 I hope to run in college and maybe even get a track scholarship.  

# social links
instagram_username: l.ena116
github_username:  lena11606

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 
